services:
  wsww:
    image: ghcr.io/rahulahoop/wsww:latest
    ports:
      - "3004:3001"
    environment:
      - NODE_ENV=production
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN}
    restart: unless-stopped
